language: python
dist: xenial
branches:
  only: [master]
before_install:
  - ./scripts/travis/tensor_serving_install.sh
  - ./scripts/travis/protoc_install.sh
  - unset PYTHONDONTWRITEBYTECODE
install:
  - pip install -e .[dev]
  - python setup.py bdist_wheel
  - pip install --no-index --find-links=dist/ min_tfs_client
before_script:
  - tensorflow_model_server --port=4080 --model_base_path=$PWD/tests/integration/fixtures && sleep 1 &
matrix:
  include:
    - name: "Tests (Python 3.6)"
      python: "3.6"
      script:
        - pytest -v tests
    - name: "Tests (Python 3.7)"
      python: "3.7"
      script:
        - pytest -v tests
    - name: "Tests (Python 3.8)"
      python: "3.8"
      script:
        - pytest -v tests
    - name: "Linting"
      python: 3.7
      script:
        - flake8 tensor_serving_client/min_tfs_client tests/