language: python
dist: xenial
python: "3.7.4"
branches:
  only: [master]
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
before_install:
  - ./scripts/travis/tensor_serving_install.sh
  - ./scripts/travis/protoc_install.sh
  - unset PYTHONDONTWRITEBYTECODE
matrix:
  include:
    - name: "Unit Tests"
      install:
        - pipenv sync --dev
        - pipenv run python setup.py bdist_wheel
        - pipenv run pip install --no-index --find-links=dist/ min_tf_client
      script:
        - pipenv run pytest -v
    - name: "Linting"
      install:
        - pipenv sync --dev
      script:
        - pipenv run flake8 tensor_serving_client/min_tf_client tests/